
const icons = {
  who: require('@assets/icons/icotab0.png'),
  what: require('@assets/icons/icotab1.png'),
  an10na: require('@assets/icons/icotab2.png'),
  watch: require('@assets/icons/icotab3.png'),
  share: require('@assets/icons/icotab4.png'),
  review: require('@assets/icons/icoreview.png'),
  apples:[
    require('@assets/icons/icoapplered.png'),
    require('@assets/icons/icoapplegreen.png'),
    require('@assets/icons/icoapplegrey.png'),
    require('@assets/icons/icoapplegold.png'),
  ],
  rating_apples_small: [
    require('@assets/icons/icoapplegoldsmall.png'),
    require('@assets/icons/icoapplegreysmall.png'),
  ],
  rating_apples: [
    require('@assets/icons/icoapplegold.png'),
    require('@assets/icons/icoapplegrey.png'),
  ],
  trend: require('@assets/icons/icotrend.png'),
  love: require('@assets/icons/icolove.png'),
  down: require('@assets/icons/icodown.png'),
  up: require('@assets/icons/icoup.png'),
  badges: [
    require('@assets/icons/badges/0.png'),
    require('@assets/icons/badges/1.png'),
    require('@assets/icons/badges/2.png'),
    require('@assets/icons/badges/3.png'),
    require('@assets/icons/badges/4.png'),
    require('@assets/icons/badges/5.png'),
    require('@assets/icons/badges/6.png'),
    require('@assets/icons/badges/7.png'),
    require('@assets/icons/badges/8.png'),
    require('@assets/icons/badges/9.png'),
    require('@assets/icons/badges/10.png'),
    require('@assets/icons/badges/11.png'),
    require('@assets/icons/badges/12.png'),
    require('@assets/icons/badges/13.png'),
    require('@assets/icons/badges/14.png'),
    require('@assets/icons/badges/15.png'),
    require('@assets/icons/badges/16.png'),
    require('@assets/icons/badges/17.png'),
    require('@assets/icons/badges/18.png'),
    require('@assets/icons/badges/19.png'),
  ],
};

export default icons;
